name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '15.0'

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2017-workload-vctools -y
        choco install visualstudio2017buildtools -y

    - name: Build solution
      run: |
        msbuild src/INAV-X-Plane-HITL-Plugin.sln /p:Configuration=Debug

    - name: Delete win.ilk and  win.pdb
      run: |
        if (Test-Path "release\Aircraft\Extra Aircraft\NK_FPVSurfwing\plugins\INAV-X-Plane-HITL\64\win.ilk") {
          Remove-Item "release\Aircraft\Extra Aircraft\NK_FPVSurfwing\plugins\INAV-X-Plane-HITL\64\win.ilk" -Force
        }
        if (Test-Path "release\Aircraft\Extra Aircraft\NK_FPVSurfwing\plugins\INAV-X-Plane-HITL\64\win.pdb") {
          Remove-Item "release\Aircraft\Extra Aircraft\NK_FPVSurfwing\plugins\INAV-X-Plane-HITL\64\win.pdb" -Force
        }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Windows
        path: release/**

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install -y ninja-build cmake gcc g++ libgl-dev libglu1-mesa-dev libalut-dev libgtk-3-dev pkg-config

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -GNinja -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
        ninja

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Linux
        path: release/**

  build-mac:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: brew install ninja cmake gtk+3 openal-soft
 
    - name: Build the project
      run: |
        make build
        cd build
        cmake -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
        ninja

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Mac
        path: release/**
