name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '15.0'

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2017-workload-vctools -y
        choco install visualstudio2017buildtools -y

    - name: Build solution
      run: |
        msbuild src/INAV-X-Plane-HITL-Plugin.sln /p:Configuration=Debug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Windows
        path: D:/Games/X-Plane11/X-Plane 11/**

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install -y make gcc g++ libgl-dev libglu1-mesa-dev libalut-dev libgtk-3-dev pkg-config

    - name: Build the project
      run: |
        cd src
        make lin64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Linux
        path: release/**

  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
        run: brew install make

    - name: Build the project
      run: |
        cd src
        make mac64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Mac
        path: release/**
