name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '15.0'

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2017-workload-vctools -y
        choco install visualstudio2017buildtools -y

    - name: Build solution
      run: |
        msbuild src/INAV-X-Plane-HITL-Plugin.sln /p:Configuration=Debug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: INAV-HITL-Windows
        path: D:/Games/X-Plane11/X-Plane 11/Aircraft/Extra Aircraft/NK_FPVSurfwing/**
