name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vsVersion: '16.0'  # версия Visual Studio 2019

    - name: Build solution
      run: |
        msbuild src/INAV-X-Plane-HITL-Plugin.sln /p:Configuration=Debug
