name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -o igncr '{0}'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake ninja gcc-g++ cmake libgl-devel libglut-devel libgtk3-devel pkg-config
      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake -GNinja -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
          ninja
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: INAV-HITL-Windows
          path: release/**

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install -y ninja-build cmake gcc g++ libgl-dev libglu1-mesa-dev libalut-dev libgtk-3-dev pkg-config

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -GNinja -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
        ninja

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Linux
        path: release/**

  build-mac:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: brew install ninja cmake gtk+3 openal-soft
 
    - name: Build the project
      run: |
        make build
        cd build
        cmake -GNinja -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
        ninja

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: INAV-HITL-Mac
        path: release/**
